default_context:
  name: "gempy"
  version: "0.1.0"
  slug: "gempy"
  command: "gempy"
  cli: "argparse"
  config: "y"
  compat: "bpyutils"
  jupyter: "n"
  sqlite: "n"
  pypy: "y"
  description: ""
  author: ""
  email: ""
  keywords: ""
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: ""
  repo_service_reponame: "gempy"
  docker_service_username: ""
  docker_service_reponame: "gempy"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com//gempy"