default_context:
  name: "gempy"
  version: "0.1.0"
  slug: "gempy"
  command: "gempy"
  cli: "argparse"
  config: "y"
<<<<<<< HEAD
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "Genome-Scale Metabolic Modelling"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "genome-scale metabolic modelling"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "gempy"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "gempy"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/gempy"
=======
  compat: "bpyutils"
  jupyter: "n"
  sqlite: "n"
  pypy: "y"
  description: ""
  author: ""
  email: ""
  keywords: ""
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: ""
  repo_service_reponame: "gempy"
  docker_service_username: ""
  docker_service_reponame: "gempy"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com//gempy"
>>>>>>> template/master
