default_context:
  name: "dgemm"
  version: "0.1.0"
  slug: "dgemm"
  command: "dgemm"
  cli: "argparse"
  config: "y"
  compat: "upyog"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  description: "Genome-Scale Metabolic Modelling"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "genome-scale metabolic modelling"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "dgemm"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "dgemm"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/dgemm"
