name: Template

on:
  push:
  
jobs:
  template:
    name: Template
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    container:
      image: ghcr.io/achillesrasquinha/bpyutils

    steps:
      - uses: actions/checkout@v3
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Updating template
        run: |
          echo "Updating template..."
          bpyutils --update-boilpy-project $GITHUB_WORKSPACE
=======
=======
>>>>>>> template/master
=======
>>>>>>> template/master
    steps:
      - uses: achillesrasquinha/boilpy-action@develop
      - name: Updating template
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
          echo "Updating template..."
>>>>>>> template/master
=======
          echo "Updating template..."
>>>>>>> template/master
=======
          echo "Updating template..."
>>>>>>> template/master
